# Generated by Django 4.2.6 on 2024-10-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_rule_rulenode_delete_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('operator', 'Operator'), ('operand', 'Operand')], max_length=10)),
                ('operator', models.CharField(blank=True, max_length=5, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_node', to='rules.node')),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_node', to='rules.node')),
            ],
        ),
        migrations.RemoveField(
            model_name='rulenode',
            name='left',
        ),
        migrations.RemoveField(
            model_name='rulenode',
            name='right',
        ),
        migrations.RemoveField(
            model_name='rulenode',
            name='rule',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='RuleNode',
        ),
    ]
